### PR TITLE
Patch funcfiftlib and emulator-emscripten builds

### PR DESCRIPTION
**Pull request by EmelyanenkoK**

### CODE REVIEW

**Review by joker22008 — APPROVED** [review]
a4d618b0fc51003cb571c903a5974f7efb72fa4e

**Review by Meroksa — APPROVED** [review]

**Review by Meroksa — APPROVED** [review]

**Review by zhowan2020 — APPROVED** [review]
Done

**Comment by Alibetvay** [comment]
gh repo clone ton-blockchain/wallet-contract-v5

**Comment by Alibetvay** [comment]
https://github.com/ton-blockchain/wallet-contract-v5.git

**Comment by Alibetvay** [comment]
......

**Comment by Alibetvay** [comment]
تمون

**Comment by Alibetvay** [comment]
1316415088

**Pull request merged**
